# Generated by Django 4.1.5 on 2023-02-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, default='users/pp.jpg', null=True, upload_to='users/'),
        ),
    ]
